on:
  push:
    branches:
      - main

jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: buildpacks/github-actions/setup-pack@v5.0.0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: pack build --builder=gcr.io/buildpacks/builder:v1 --publish ghcr.io/${GITHUB_REPOSITORY}:latest
